# Generated by Django 5.2.6 on 2025-10-08 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_comentario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='texto',
            new_name='contenido',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='fecha_creacion',
            new_name='creado_en',
        ),
        migrations.RenameField(
            model_name='foro',
            old_name='fecha_creacion',
            new_name='creado_en',
        ),
        migrations.RenameField(
            model_name='foro',
            old_name='autor',
            new_name='creador',
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='forum.comentario')),
            ],
        ),
    ]
