# Generated by Django 5.2.6 on 2025-10-08 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_rename_texto_comentario_contenido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='creado_en',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='foro',
            old_name='creador',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='foro',
            old_name='creado_en',
            new_name='fecha_creacion',
        ),
        migrations.DeleteModel(
            name='Respuesta',
        ),
    ]
