# Generated by Django 5.2.6 on 2025-10-08 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_rename_creado_en_comentario_fecha_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='contenido',
            new_name='texto',
        ),
    ]
