# Generated by Django 5.2.6 on 2025-10-10 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_rename_contenido_comentario_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='foro',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='foros/'),
        ),
    ]
