# Generated by Django 5.2.7 on 2025-10-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_alter_foro_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='foro',
            name='fijado',
            field=models.BooleanField(default=False),
        ),
    ]
