# Generated by Django 5.2.7 on 2025-10-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_foro_fijado'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='comentarios_archivos/'),
        ),
    ]
