# Generated by Django 5.2.7 on 2025-10-18 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialDidactico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('PDF', 'PDF'), ('Presentación', 'Presentación'), ('Video', 'Video'), ('Enlace', 'Enlace'), ('Otro', 'Otro')], max_length=50)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='materiales/')),
                ('enlace', models.URLField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
