# Generated by Django 5.2.7 on 2025-11-14 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_entregaalumno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entregaalumno',
            options={},
        ),
        migrations.RenameField(
            model_name='entregaalumno',
            old_name='fecha_entrega',
            new_name='fecha_subida',
        ),
        migrations.RemoveField(
            model_name='entregaalumno',
            name='calificacion',
        ),
        migrations.RemoveField(
            model_name='entregaalumno',
            name='comentario_profesor',
        ),
        migrations.RemoveField(
            model_name='entregaalumno',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='entregaalumno',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='entregaalumno',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entregaalumno',
            name='archivo',
            field=models.FileField(upload_to='entregas/'),
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('video', 'Video'), ('lectura', 'Lectura'), ('tarea', 'Tarea'), ('examen', 'Examen')], max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='dashboard.curso')),
            ],
        ),
    ]
