# Generated by Django 5.2.7 on 2025-10-26 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_curso_options_curso_alumnos_inscritos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.RemoveField(
            model_name='curso',
            name='alumnos_inscritos',
        ),
        migrations.AlterField(
            model_name='curso',
            name='categoria',
            field=models.CharField(choices=[('Ciencias', 'Ciencias'), ('Matemáticas', 'Matemáticas'), ('Programación', 'Programación'), ('Idiomas', 'Idiomas'), ('Física', 'Física'), ('Música', 'Música')], default='Ciencias', max_length=50),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='curso',
            name='grupo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
