# Generated by Django 5.2.7 on 2025-10-28 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_evaluacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='materiales',
            field=models.ManyToManyField(blank=True, related_name='evaluaciones_asignadas', to='dashboard.materialdidactico'),
        ),
    ]
