# core/settings.py
"""
Django settings for core project.
Generated by 'django-admin startproject' using Django 5.2.6.
"""
# Configuración actualizada el 10/10/2025
import os
from pathlib import Path
from datetime import timedelta

# Build paths inside the project
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'local-secret')
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [
    '3.146.150.176',
    '127.0.0.1',
    'localhost',
    'ec2-3-146-150-176.us-east-2.compute.amazonaws.com',
    'educonnect.duckdns.org'
]

# reCAPTCHA Keys
RECAPTCHA_SITE_KEY = "6LeyVfgrAAAAAB5DRsBe_KfPoqC1XsTv9y32iL4a"
RECAPTCHA_SECRET_KEY = "6LeyVfgrAAAAAAeSflieGqqrffSw9-i_tzWIJMgG"

# Application definition
INSTALLED_APPS = [
    'jazzmin',  # Tema personalizado para el admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'axes',

    # Tus apps personalizadas
    'landing',
    'auth_app',
    'dashboard',
    'resources',
    'forum',
    'analytics',
    'ai',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # ✅ Agregar CORS aquí
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'axes.middleware.AxesMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "core" / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# ----------------------
# Database flexible
# ----------------------
if os.environ.get('DJANGO_PRODUCTION') == 'True':
    # Producción: PostgreSQL/RDS
    DATABASES = {
        'default': {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": "postgres",
            "USER": "postgres",
            "PASSWORD": "admin404",
            "HOST": "db-educonect-free.c1uegi2mqp0w.us-east-2.rds.amazonaws.com",
            "PORT": "5432",
        }
    }
else:
    # Desarrollo local: SQLite
    DATABASES = {
        'default': {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 6,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'es-es'  # Cambiado a español
TIME_ZONE = 'America/Mexico_City'  # O tu zona horaria
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Login redirects
LOGIN_URL = '/auth/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/auth/login/'

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',  # ✅ Axes debe ir primero
    'django.contrib.auth.backends.ModelBackend',
]

# Axes configuration (protección contra ataques de fuerza bruta)
AXES_FAILURE_LIMIT = 5  # Número de intentos fallidos antes de bloquear
AXES_COOLOFF_TIME = timedelta(minutes=15)  # Tiempo de bloqueo
AXES_RESET_ON_SUCCESS = True

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

CORS_ALLOW_CREDENTIALS = True

# REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ]
}

# JWT Configuration
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
}

# Jazzmin Admin Configuration
JAZZMIN_SETTINGS = {
    "site_title": "EduConnect+ Admin",
    "site_header": "Panel de Administración EduConnect+",
    "site_brand": "EduConnect+",
    "site_logo": "vendor/adminlte/img/AdminLTELogo.png",
    "welcome_sign": "Bienvenido al sistema de gestión EduConnect+",
    "copyright": "© 2025 EduConnect",
    "search_model": "auth.User",
    
    # Tema y colores
    "theme": "darkly",
    "dark_mode_theme": "darkly",
    
    # Personalización de UI
    "show_ui_builder": False,
    
    # Organización de apps
    "order_with_respect_to": [
        "dashboard",
        "resources",
        "forum",
        "auth",
    ],
    
    # Íconos personalizados
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "dashboard": "fas fa-tachometer-alt",
        "resources": "fas fa-book",
        "forum": "fas fa-comments",
    },
    
    # Menú lateral
    "navigation_expanded": True,
    "topmenu_links": [
        {"name": "Inicio", "url": "/", "permissions": ["auth.view_user"]},
        {"name": "Documentación", "url": "https://docs.djangoproject.com/en/5.2/", "new_window": True},
        {"app": "auth"},
    ],
}

JAZZMIN_UI_TWEAKS = {
    "theme": "darkly",
    "navbar": "navbar-dark",
    "navbar_fixed": True,
    "sidebar_fixed": True,
    "sidebar": "dark",
    "footer_fixed": False,
    "body_small_text": True,
    "brand_color": "navbar-primary",
    "accent": "accent-info",
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-outline-info",
        "success": "btn-outline-success",
        "warning": "btn-outline-warning",
        "danger": "btn-outline-danger",
    },
}
# Security settings for production
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

# Axes configuration (protección contra ataques de fuerza bruta) - SOLO UNA VEZ
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = timedelta(minutes=30)
AXES_RESET_ON_SUCCESS = True
AXES_LOCKOUT_PARAMETERS = [["username"]]  # ✅ CORREGIDO: lista de listas
AXES_LOCKOUT_CALLABLE = "auth_app.utils.lockout_response"
AXES_COOLOFF_MESSAGE = "Demasiados intentos fallidos. Por favor espera 30 minutos."

# ELIMINA estas líneas duplicadas:
# AXES_USE_USER_AGENT = True  # ❌ ESTÁ DEPRECADA

AXES_NEVER_LOCKOUT_WHITELIST = [
    '127.0.0.1',
    '3.146.150.176',
]

AXES_VERBOSE = True

# Logging de intentos fallidos
AXES_VERBOSE = True
# ✅ AGREGAR esta configuración importante:
AXES_HANDLER = 'axes.handlers.database.AxesDatabaseHandler'
AXES_LOCKOUT_TEMPLATE = None
AXES_LOCKOUT_URL = None
# Security headers
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_REFERRER_POLICY = 'same-origin'

# CORS settings más estrictos
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000", 
    "http://127.0.0.1:8000",
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'PUT', 
    'PATCH',
    'DELETE',
    'OPTIONS'
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]
# CSRF settings
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'https://educonnect.duckdns.org',
    'https://3.146.150.176',
]

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'security_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'security.log',
        },
    },
    'loggers': {
        'security': {
            'handlers': ['security_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


# Security settings for production
if not DEBUG:
    # HTTPS settings
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # HSTS settings
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Additional security
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')