# Generated by Django 5.2.7 on 2025-10-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
