# Generated by Django 5.2.7 on 2025-10-16 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_remove_perfilusuario_institucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='institucion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
