# Generated by Django 5.2.7 on 2025-10-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_perfilusuario_is_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='alias',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='semestre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
