# Generated by Django 5.2.7 on 2025-10-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_perfilusuario_institucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='img/default_user.png', null=True, upload_to='perfiles/'),
        ),
    ]
