# Generated by Django 5.2.7 on 2025-10-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_perfilusuario_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='idioma',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'Inglés')], default='es', max_length=20),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='modo_visualizacion',
            field=models.CharField(choices=[('claro', 'Claro'), ('oscuro', 'Oscuro')], default='claro', max_length=20),
        ),
    ]
