# Generated by Django 5.2.7 on 2025-10-16 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_perfilusuario_idioma_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='idioma',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='modo_visualizacion',
        ),
    ]
