# Generated by Django 5.2.7 on 2025-11-14 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EntregaAlumno',
        ),
    ]
