# Generated by Django 5.2.6 on 2025-10-04 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recursos',
            name='completado',
        ),
        migrations.RemoveField(
            model_name='recursos',
            name='creador',
        ),
        migrations.RemoveField(
            model_name='recursos',
            name='descargable',
        ),
        migrations.RemoveField(
            model_name='recursos',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='recursos',
            name='url',
        ),
    ]
