# Generated by Django 5.2.6 on 2025-10-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_remove_recursos_completado_remove_recursos_creador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recursos',
            name='completado',
            field=models.BooleanField(default=False),
        ),
    ]
