# Generated by Django 5.2.6 on 2025-10-09 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_recursos_completado'),
    ]

    operations = [
        migrations.AddField(
            model_name='recursos',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='recursos/'),
        ),
    ]
