# Generated by Django 5.2.7 on 2025-10-29 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_entregaalumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregaalumno',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='entregaalumno',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
