# Generated by Django 5.2.7 on 2025-10-29 08:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_entregaalumno_tipo_alter_entregaalumno_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='recursos',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
